version: "3.7"

services:
  django:
    build: .
    container_name: django
    command: gunicorn --bind :8000 YTapi.wsgi 
    
    volumes: 
      - .:/usr/src/YTAPI/
      
    ports: 
      - 8000:8000
    
    env_file: 
      - ./YTapi/.env
    
    depends_on: 
      - mongodb
      - redis
      - elasticsearch

  mongodb:
    image: mongo
    volumes: 
      - mongodb-data:/usr/share/mongodb-data/
    ports: 
      - 27017:27017


  celery:
    build: .
    container_name: celery
    command: ['celery', '-A', 'YTapi', 'worker', '-l', 'INFO']
    volumes:
      - celery-data:/usr/share/celery-data/
    
    depends_on: 
      - django
      - redis
      - mongodb
    
      
  celery-beat:
    build: .
    container_name: celery-beat
    command: ['celery', '-A', 'YTapi', 'beat', '-l', 'INFO']
    volumes:
      - celery-data:/usr/share/celery-data/
    
    depends_on: 
      - django
      - redis
      - mongodb
    
  
  redis:
    image: redis:alpine
    container_name: redis


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    container_name: elasticsearch
    volumes:
      - es-data:/usr/share/elasticsearch/
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      network.bind_host: 0.0.0.0
      network.host: 0.0.0.0
      discovery.type: single-node
      http.max_content_length: 1000mb 
      xpack.security.enabled: 'false'

volumes: 
  mongodb-data:
  celery-data:
  es-data:
  