# Generated by Django 3.0.5 on 2021-05-20 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('number', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='YTVideo',
            fields=[
                ('video_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('channel_title', models.CharField(max_length=100)),
                ('video_title', models.CharField(max_length=200)),
                ('video_description', models.TextField(max_length=500)),
                ('publish_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_query', to='api.SearchQuery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_query', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
