# Generated by Django 3.0.5 on 2021-05-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210520_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquery',
            name='videos',
        ),
    ]
