# Generated by Django 3.0.5 on 2021-05-20 15:42

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_userquery_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchquery',
            name='number',
        ),
        migrations.AddField(
            model_name='searchquery',
            name='videos',
            field=djongo.models.fields.ArrayField(default=['Checking'], model_container=api.models.YTVideo),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userquery',
            name='query',
            field=models.CharField(max_length=100),
        ),
    ]
