# Generated by Django 3.0.5 on 2021-05-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210520_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchquery',
            name='videos',
        ),
    ]
