# Generated by Django 3.0.5 on 2021-05-20 15:46

import api.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_searchquery_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='videos',
            field=djongo.models.fields.ArrayField(default=['H', 'e', 'l', 'l', 'o'], model_container=api.models.YTVideo),
            preserve_default=False,
        ),
    ]
