# Generated by Django 3.0.5 on 2021-05-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_searchquery_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchquery',
            name='video',
        ),
        migrations.AddField(
            model_name='searchquery',
            name='video',
            field=models.ManyToManyField(to='api.YTVideo'),
        ),
    ]
